.\" Copyright 2002 Walter Harms (walter.harms@informatik.uni-oldenburg.de)
.\" Dystrybuowane zgodnie z licencją GPL
.\"
.TH CEXP 3 2002-07-28 "" "zespolone funkcje matematyczne"
.SH NAZWA
cexp, cexpf, cexpl \- zespolona funkcja wykladnicza
.SH SKŁADNIA
.B #include <complex.h>
.sp
.BI "double complex cexp(double complex " z ");"
.br
.BI "float complex cexpf(float complex " z ");"
.br
.BI "long double complex cexpl(long double complex " z ");"
.sp
Parametr dla linkera: \-lm.
.SH OPIS
Funkcja wylicza e (2.71828..., podstawę logarytmu naturalnego)
podniesione do potęgi z.
.LP
Według wzoru: cexp(I*z) = ccos(z) + I*csin(z).
.SH "ZGODNE Z"
C99
.SH "ZOBACZ RÓWNIEŻ"
.BR cabs (3),
.BR clog (3),
.BR cpow (3),
.BR complex (7)
.SH TŁUMACZENIE
Paweł Sędrowski
.br
Projekt Tłumaczenia Manuali
.br
http://ptm.berlios.de