.\" Copyright 2002 Walter Harms (walter.harms@informatik.uni-oldenburg.de)
.\" Dystrybuowane zgodnie z licencją GPL
.\"
.TH CREAL 3 2002-07-28 "" "zespolone funkcje matematyczne"
.SH NAME
creal, crealf, creall \- zwraca część rzeczywistą liczby zespolonej
.SH SKŁADNIA
.B #include <complex.h>
.sp
.BI "double creal(double complex " z );
.br
.BI "float crealf(float complex " z );
.br
.BI "long double creall(long double complex " z );
.sp
Parametr dla linkera: \-lm.
.SH OPIS
Funkcja
.BR creal ()
Zwraca część rzeczywistą liczby zespolonej z.
.LP
Według wzoru: z = creal(z) + I*cimag(z).
.SH NOTE
The gcc supports also __real__. That is a GNU extension. 
.SH "ZGODNE Z"
C99
.SH "ZOBACZ RÓWNIEŻ"
.BR cabs (3),
.BR cimag (3),
.BR complex (7)
.SH TŁUMACZENIE
Paweł Sędrowski
.br
Projekt Tłumaczenia Manuali
.br
http://ptm.berlios.de