.\" Copyright 2002 Walter Harms (walter.harms@informatik.uni-oldenburg.de)
.\" Dystrybuowane zgodnie z licencją GPL
.\"
.TH CSINH 3 2002-07-28 "" "zespolone funkcje matematyczne"
.SH NAZWA
csinh, csinhf, csinhl \- zespolony sinus hiperboliczny
.SH SKŁADNIA
.B #include <complex.h>
.sp
.BI "double complex csinh(double complex " z ");"
.br
.BI "float complex csinhf(float complex " z ");"
.br
.BI "long double complex csinhl(long double complex " z ");"
.sp
Parametr dla linkera: \-lm.
.SH OPIS
Funkcja zespolonego sinusa hiperbolicznego sinh(z) jest zdefniowana jako
(exp(z)\-exp(\-z))/2. 
.SH "ZGODNE Z"
C99
.SH "ZOBACZ RÓWNIEŻ"
.BR cabs (3),
.BR ccosh (3),
.BR ctanh (3),
.BR complex (7)
.SH TŁUMACZENIE
Paweł Sędrowski
.br
Projekt Tłumaczenia Manuali
.br
http://ptm.berlios.de