.\" Copyright 2002 Walter Harms (walter.harms@informatik.uni-oldenburg.de)
.\" Dystrybuowane zgodnie z licencją GPL
.\"
.TH FMIN 3 2002-07-28 "" "funkcje matematyczne"
.SH NAZWA
fmin, fminf, fminl \- znajduje najmniejszą wartość
.SH SKŁADNIA
.B #include <math.h>
.sp
.BI "double fmin(double " x ", double " y );
.br
.BI "float fminf(float " x ", float " y );
.br
.BI "long double fminl(long double " x ", long double " y );
.sp
Parametr dla kompilatora: \-std=c99; parametr dla linkera: \-lm.
.SH OPIS
Znajduje mniejszą wartość spośród x i y.
.SH "ZGODNE Z"
C99
.SH "ZOBACZ RÓWNIEŻ"
.BR fmax (3)
.SH TŁUMACZENIE
Paweł Sędrowski
.br
Projekt Tłumaczenia Manuali
.br
http://ptm.berlios.de