.\" $Id: bash-completion-config.1.in 78 2004-12-01 10:36:58Z ka0ttic $
.TH "bash-completion-config" 1 "Jan 2005" "0.8"
.SH NAME
\fBbash-completion-config\fR \- Add/remove bash-completion functions to your environment.
.SH SYNOPSIS
.B "bash-completion-config "
[ \fIoptions\fR ] [ <\fIbashcomp1\fR> <\fIbashcomp2\fR> ...  ]
.SH DESCRIPTION
\fBbash-completion-config\fR attempts to ease installation and configuration of contributed
(ie not include in bash-completion proper) bash completions and allows for both
per-user and system-wide (see --global) installations.
.SH OPTIONS
.TP
.B "\-h, \-\-help"
Display usage information.
.TP
.B "\-V, \-\-version"
Display version.
.TP
.B "\-nc, \-\-nocolor, \-\-nocolour"
Disable colored output.
.TP
.B "\-g, \-\-global"
Perform specified operation on a system-wide basis.  Must be used in conjunction
with --install or --uninstall.
.TP
.B "\-d, \-\-debug"
Enable debug-mode, which among other things, sets the bash options 'verbose' and 'xtrace'.
If you encounter a bug, please send the output of bash-completion-config when run with this option set,
along with your bug report.
.TP
.B "\-l, \-\-list"
List currently installed completions (local and global).  This option takes an
optional argument, 'all', which if specified lists all completions, not just those
installed.
.TP
.B "\-i, \-\-install"
Install specified completion(s).  Takes an arbitrary number of completions to
install.  Each argument may be a path, or just a name, in which case it will
be assumed to exist in /usr/share/bash-completion.  Installs locally, unless
--global is previously specified.
.TP
.B "\-u, \-\-uninstall"
Uninstall specified completion(s).  Takes an arbitrary number of completions
to uninstall.  Each argument should be just the name of the completion.  
Uninstalls locally, unless --global is previously specified.
.SH ENVIRONMENT
.TP
.B BASHCOMP_DIR
Location of contributed bash completions.  Defaults to /usr/share/bash-completion.
.TP
.B INSTALL_DIR
Location of local installation directory.  Defaults to $HOME/.bash_completion.d.
.TP
.B GLOBAL_INSTALL_DIR
Location of global installation directory.  Defaults to /etc/bash_completion.d.
.SH CONFIGURATION
Any of the above variables may also be defined in a rc file, in the following format:
.br

.B VARIABLE=VALUE

\fBbash-completion-config\fR will first read /etc/bashcomp-configrc, if it exists, then
$HOME/.bashcomp-configrc, if it exists.
.SH AUTHORS
.TP
Aaron Walker <\fIka0ttic@gentoo.org\fR>
.SH SEE ALSO
.TP
.B bash(1)
.SH NOTES
Please report any bugs to http://bugs.gentoo.org/.
