.\" Translation (C) 1999 Paweł Wilk <siewca@dione.ids.pl>
.\" {PTM/PW/0.1/25-05-1999/"wypisz łańcuchy ścianki ogniowej IP na stdout"}
.\" Translation update Robert Luberda <robert@debian.org>, Jul 2004, ipchains 1.3.10
.\" $Id: ipchains-save.8,v 1.4 2004/07/16 10:03:41 robert Exp $
.\"
.TH IPCHAINS-SAVE 8 "8 lutego 1998" "" ""
.SH NAZWA
ipchains\-save \- wypisuje łańcuchy ścianki ogniowej IP na stdout
.SH SKŁADNIA
.BR "ipchains\-save " "[reguła] [ -v ]
.SH OPIS
ipchains\-save wypisuje łańcuchy ścianki ogniowej IP na standardowe wyjście
.SH OPCJE
Opcje rozpoznawane przez
.B ipchains-save
to:
.TP
.BR -v
drukuje każdą regułę
.P
Opcjonalnie podana nazwa reguły oznacza, że zachowana będzie tylko
ta reguła.
.SH ZOBACZ TAKŻE
ipchains(8), IPCHAINS HOWTO.
.SH AUTOR
Paul ``Rusty'' Russell <ipchains@rustcorp.com>
