.\" {PTM/WK/1999-XII}
.Id $Id: atd.8,v 1.2 2001/02/06 17:16:05 wojtek2 Exp $
.TH ATD 8 "marzec 1997" local "Podręcznik Programisty Linuksa"
.SH NAZWA
atd \- uruchom zadania kolejkowane do późniejszego wykonania
.SH SKŁADNIA
.B atd
.RB [ -l
.IR load_avg ]
.RB [ -b
.IR batch_interval ]
.RB [ -d ]
.RB [ -s ]
.SH OPIS
.B atd
uruchamia zadania kolejkowane przez
.BR at(1) .
.PP
.SH OPCJE
.TP
.B -l
Określa ograniczenie wskaźnika obciążenia (load factor), powyżej którego
zadania wsadowe nie powinny być uruchamiane, zamiast wyboru wbudowanego
wskaźnika 0.8.
Dla systemów SMP z
.I n
CPU, zechcesz zapewne ustawić go wyżej niż
.IR n-1.
.TP
.B -b
Określa minimalny odstęp w sekundach pomiędzy startem dwu zadań wsadowych
(domyślnie 60).
.TP
.B -d
Debug; wyświetla komunikaty o błędach na standardowe wyjście błędów zamiast
wykorzystywania
.BR syslog(3) .
.TP
.B -s
Przetwarza kolejkę at/batch tylko jednokrotnie. Służy głównie do uzyskania
zgodności ze starszymi wersjami
.BR at ;
.B "atd -s"
jest równoważne staremu poleceniu
.BR atrun .
Dla celów wstecznej zgodności jako
.B /usr/sbin/atrun
instalowany jest skrypt wywołujący
.BR "atd -s" .
.SH OSTRZEŻENIE
\fBatd\fP nie będzie działąć jeśli katalog do przechowywania wyników
jest zamontowany poprzez NFS, nawet jeżeli ustawiono \fBno_root_squash\fP.
.SH PLIKI
.I /var/spool/atjobs
Katalog przechowujący zadania; powinien posiadać prawa dostępu 700
i właściciela at.
.PP
.I /var/spool/atspool
Katalog przechowujący wyniki (wyjście); powinien posiadać prawa dostępu 700
i właściciela at.
.PP
.IR /etc/at.allow ,
.IR /etc/at.deny
określają, kto może posługiwać się systemem
.BR at .
.SH ZOBACZ TAKŻE
.BR at (1),
.BR atrun (1),
.BR cron (8),
.BR crontab (1),
.BR syslog (3),
.BR at_deny (5),
.BR at_allow(5).
.SH BŁĘDY
Funkcjonalność
.B atd
powinna być wcielona do
.BR cron (8).
