.\" {PTM/PB/0.1/02-10-1998/"utwórz, modyfikuj i ekstrachuj z archiwów"}
.\" Translation 1998 Przemek Borys <pborys@dione.ids.pl>
.TH clear 1 ""
.ds n 5
.SH NAZWA
\fBclear\fR - wyczyść ekran terminala
.SH SKŁADNIA
\fBclear\fR
.br
.SH OPIS
\fBclear\fR czyści ekran terminala (o ile to możliwe). Sprawdza on w
środowisku typ terminala, a potem w bazie \fBterminfo\fR szuka sposobu na
wyczyszczenie ekranu.
.SH ZOBACZ TAKŻE
\fBtput\fR(1), \fBterminfo\fR(\*n)
.\"#
.\"# The following sets edit modes for GNU EMACS
.\"# Local Variables:
.\"# mode:nroff
.\"# fill-column:79
.\"# End:
