.\" {PTM/WK/1999-10-20}
.\" -*- nroff -*-
.TH kmalloc 9 "3 sierpnia 1997" "Linux" "Funkcje jądra"
.SH NAZWA
kmalloc, kfree \- alokuj i zwolnij obszar pamięci
.SH SKŁADNIA
.B #include <linux/malloc.h>
.sp
.BI "void * kmalloc (size_t " size ", int " priority ");"
.br
.BI "void kfree (void * " __ptr ");"
.SH OPIS
Funkcja
.B kmalloc
alokuje fragment pamięci.
.PP
Parametr
.I size
jest liczbą bajtów, jakie zostaną zaalokowane. Parametr
.I priority
wskazuje na wagę i typ żądania pamięci. Niektórymi możliwymi
wartościami są GFP_DMA, GFP_ATOMIC, GFP_BUFFER i GFP_NFS.
.PP
Funkcja
.B kfree
zwalnia obszar pamięci przesłany jako parametr
.IR __ptr .
.SH WARTOŚĆ ZWRACANA
W przypadku powodzenia,
.B kmalloc
zwraca wskaźnik do świeżo zaalokowanej pamięci.
.PP
W przypadku błędu zamiast wskaźnika do pamięci zwracany jest NULL.
.PP
.SH DOSTĘPNOŚĆ
Linux 2.0
.SH AUTOR
Kirk Petersen (kirk@speakeasy.org)
