.\" {PTM/RM//31-08-2000}
.TH RVNAMED 8 "Strona pomocy do rvnamed"
.SH NAZWA
rvnamed \- deamon rozwiązywania domen odwrotnych dla
.BR iptraf (8)

.SH OPIS
.B rvnamed
jest programem dystrybuowanym z iptraf. Używany - w tle - do
"zamiany" adresów IP na nazwy hostów. Wyręcza iptraf. 
.PP
Ten program jest uzywany TYLKO przez iptraf i absolutnie
nieużyteczny w innej postaci.

.SH PLIKI
/var/local/iptraf/rvnamed.log - plik dziennika

.SH ZOBACZ TAKŻE
README.rvnamed - dokumentacja napisana przez autora
.br

.SH AUTOR
Gerard Paul Java (riker@mozcom.com)

.SH AUTOR MANUAL-a
Frederic Peters (fpeters@debian.org), na podstawie README.rvnamed.
Ogólne modyfikacje Gerard Paul Java (riker@mozcom.com)

