.\" {PTM/PB/0.2/01-06-1999/"Drukuj trasę pakietów"}
.\" Translation (c) 1999 Przemek Borys <pborys@dione.ids.pl>
.\" Copyright (c) 1990, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
.\"
.\" This code is derived from software contributed to Berkeley by
.\" Van Jacobson.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"	This product includes software developed by the University of
.\"	California, Berkeley and its contributors.
.\" 4. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"     @(#)traceroute.8	8.1 (Berkeley) 6/6/93
.\"
.Dd 6 Czerwiec, 1993
.Dt TRACEROUTE 8
.Os BSD 4.3
.Sh NAZWA
.Nm traceroute
.Nd drukuj trasę, którą przebiegają pakiety do hosta sieciowego
.Sh SKŁADNIA
.Nm traceroute
.Op Fl m Ar max_ttl
.Op Fl n
.Op Fl p Ar port
.Op Fl q Ar nqueries
.Op Fl r
.Bk -words
.Op Fl s Ar src_addr
.Ek
.Op Fl t Ar tos
.Op Fl w Ar waittime
.Ar host
.Op Ar packetsize
.Sh OPIS
Internet jest wielką i skomplikowaną agregacją sprzętu sieciowego,
połączonego ze sobą poprzez bramki (gateways). Śledzenie trasy, którą
podążają pakiety danej osoby (lub znajdywanie paskudnej bramki, odrzucającej
twoje pakiety) może być trudne.
.Nm Traceroute
wykorzystuje pole `time to live' protokołu IP i próbuje wydobyć odpowiedź
.Tn ICMP
.Dv TIME_EXCEEDED
od każdej bramki na drodze do określonego hosta.
.Pp
Jedynym wymaganym parametrem jest nazwa hosta docelowego lub jego IP.
Domyślny próbny datagram ma długość 38 bajtów, lecz może to być zwiększone
przez podanie rozmiaru pakietu za nazwą hosta docelowego.
.Pp
Inne opcje to:
.Bl -tag -width Ds
.It Fl m Ar max_ttl
Ustaw maksymalny time-to-live (ttl - `czas życia' maksymalna liczba
skoków - hops) używany w wychodzących pakietach próbnych. Domyślnie używa się
wartości 30 (podobnie jak dla połączeń
.Tn TCP
).
.It Fl n
Drukuj adresy skoków (hops) numerycznie zamiast symbolicznie i numerycznie
(oszczędza szukania w DNS skojarzenia adres-nazwa dla każdej napotkanej
po drodze bramki).
.It Fl p Ar port
Ustaw podstawowy numer
.Ar portu
.Tn UDP
używanego w próbkach (domyślnie 33434).
.Nm Traceroute
ma nadzieję, że nic nie nasłuchuje na portach 
.Tn UDP
od
.Em base
do
.Em base+nhops-1
na hoście docelowym (tak, że zwracany będzie komunikat
.Tn ICMP
.Dv PORT_UNREACHABLE
, kończący śledzenie trasy). Jeśli coś nasłuchuje na porcie w domyślnym
zakresie, opcja ta może być użyta do wybrania nieużywanego zakresu.
.It Fl q Ar nqueries
Ustaw liczbę prób na każde `ttl' na
.Ar nqueries
(domyślnie trzy próby).
.It Fl r
Obejdź normalne tablice trasowania (routingu) i wysyłaj bezpośrednio do
hosta w przyłączonej sieci.
Jeśli host nie znajduje się w bezpośrednio przyłączonej sieci, zwracany jest
błąd.
Opcja ta może być użyta do pingowania hosta lokalnego poprzez interfejs,
który nie ma przez siebie żadnej trasy (route) (np. po porzuceniu interfejsu
przez
.Xr routed 8 ) .
.It Fl s Ar src_addr
Używaj zadanego adresu IP (który musi być podany jako numer IP, nie
nazwa hosta) jako adresu źródłowego w wychodzących pakietach próbnych. Na
hostach z więcej niż jednym adresem IP, opcja ta może być używana do
wymuszania adresu źródłowego innego niż adres IP interfejsu, na którym
posyłana jest próbka. Jeśli adres IP nie jest jednym z tych adresów
interfejsowych maszyny, zwracany jest błąd i nic nie jest wysyłane.
.It Fl t Ar tos
Ustaw
.Em type-of-service
(rodzaj usługi) w pakietach próbnych na zadaną wartość (domyślnie
zero). Wartość musi być dziesiętną liczbą całkowitą z zakresu 0 do 255.
Opcja ta może być używana do sprawdzania czy różne rodzaje usług powodują
różne ścieżki (jeśli nie pracujesz z systemem
.Bx 4.3 Tahoe
lub późniejszym, może to być czysto akademickie, ponieważ normalne
usługi sieciowe, takie jak telnet i ftp nie pozwolą ci kontrolować
.Dv TOS ) .
Nie wszystkie wartości
.Dv TOS
są dozwolone lub mają znaczenie
\- zobacz specyfikację IP. Użytecznymi wartościami są prawdopodobnie
.Ql \-t 16
(low delay) (małe opóźnienie) i
.Ql \-t 8
(high throughput) (duży przepływ).
.It Fl v
Interaktywne wyjście. Listowane są odebrane pakiety
.Tn ICMP
inne niż
.Dv TIME_EXCEEDED
i
.Dv UNREACHABLE Ns s .
.It Fl w
Ustaw czas (w sekundach) oczekiwania na odpowiedź na próbkę (domyślnie 3
sekundy).
.El
.Pp
Program ten próbuje śledzić trasę pakietów IP, którą taki pakiet przebyłby
do danego hosta internetowego. Czyni to odpalając próbki
.Tn UDP
z małym ttl (time to live), a następnie nasłuchując od bramki odpowiedzi
.Tn ICMP
"time exceeded". Rozpoczynamy próbki z ttl wartości jeden i
zwiększamy je, aż otrzymamy odpowiedź
.Tn ICMP
"port unreachable"
(co znaczy, że dostaliśmy się do "hosta") lub doszliśmy do maksimum (co
domyślnie odpowiada 30 skokom i może być zmienione flagą
.Fl m
).  Dla każdego ttl wysyłane są trzy próbki (zmieniane flagą
.Fl q
), czego efektem jest wypisanie linijki, pokazującej ttl, adres bramki i
zaokrąglony czas podróży każdej z próbek. Jeśli odpowiedzi próbek przyszły
z różnych bramek, wydrukowane zostaną adresy wszystkich odpowiadających
systemów.
Jeśli nie było odpowiedzi podczas 3 sekundowego interwału (określanego jako
`timeout' i zmienianego flagą
.Fl w
), to dla danej próbki drukowane jest "*".
.Pp
Nie chcemy, by docelowy host przetwarzał próbki pakietów
.Tn UDP
, więc docelowy port jest ustawiany na wartość niespotykaną (jeśli
jakiś prostak na hoście docelowym używa jednak tej wartości, można ją zmienić
flagą
.Fl p
).
.Pp
Przykładem użycia i wyjścia może być:
.Bd -literal
[yak 71]% traceroute nis.nsf.net.
traceroute to nis.nsf.net (35.1.1.48), 30 hops max, 56 byte packet
1  helios.ee.lbl.gov (128.3.112.1)  19 ms  19 ms  0 ms
2  lilac-dmc.Berkeley.EDU (128.32.216.1)  39 ms  39 ms  19 ms
3  lilac-dmc.Berkeley.EDU (128.32.216.1)  39 ms  39 ms  19 ms
4  ccngw-ner-cc.Berkeley.EDU (128.32.136.23)  39 ms  40 ms  39 ms
5  ccn-nerif22.Berkeley.EDU (128.32.168.22)  39 ms  39 ms  39 ms
6  128.32.197.4 (128.32.197.4)  40 ms  59 ms  59 ms
7  131.119.2.5 (131.119.2.5)  59 ms  59 ms  59 ms
8  129.140.70.13 (129.140.70.13)  99 ms  99 ms  80 ms
9  129.140.71.6 (129.140.71.6)  139 ms  239 ms  319 ms
10  129.140.81.7 (129.140.81.7)  220 ms  199 ms  199 ms
11  nic.merit.edu (35.1.1.48)  239 ms  239 ms  239 ms

.Ed
Zauważ, że linie 2 i 3 są takie same. Stało się to z powodu zapluskwionego
jądra na systemie odwiedzonym w drugim skoku \- lbl-csam.arpa, które
przekazuje pakiety o zerowym ttl (błąd w rozpowszechnianej wersji
.Tn BSD 4.3
).
Zauważ, że musisz zgadywać, którą konkretnie ścieżkę obierają pakiety,
ponieważ
.Tn NSFNet
(129.140)
nie dostarcza translacji adres-na-nazwę dla swoich
.Tn NSS Ns ów .
.Pp
Ciekawszym przykładem jest:
.Bd -literal
[yak 72]% traceroute allspice.lcs.mit.edu.
traceroute to allspice.lcs.mit.edu (18.26.0.115), 30 hops max
1  helios.ee.lbl.gov (128.3.112.1)  0 ms  0 ms  0 ms
2  lilac-dmc.Berkeley.EDU (128.32.216.1)  19 ms  19 ms  19 ms
3  lilac-dmc.Berkeley.EDU (128.32.216.1)  39 ms  19 ms  19 ms
4  ccngw-ner-cc.Berkeley.EDU (128.32.136.23)  19 ms  39 ms  39 ms
5  ccn-nerif22.Berkeley.EDU (128.32.168.22)  20 ms  39 ms  39 ms
6  128.32.197.4 (128.32.197.4)  59 ms  119 ms  39 ms
7  131.119.2.5 (131.119.2.5)  59 ms  59 ms  39 ms
8  129.140.70.13 (129.140.70.13)  80 ms  79 ms  99 ms
9  129.140.71.6 (129.140.71.6)  139 ms  139 ms  159 ms
10  129.140.81.7 (129.140.81.7)  199 ms  180 ms  300 ms
11  129.140.72.17 (129.140.72.17)  300 ms  239 ms  239 ms
12  * * *
13  128.121.54.72 (128.121.54.72)  259 ms  499 ms  279 ms
14  * * *
15  * * *
16  * * *
17  * * *
18  ALLSPICE.LCS.MIT.EDU (18.26.0.115)  339 ms  279 ms  279 ms

.Ed
Zauważ, że bramki 12, 14, 15, 16 i 17 albo nie przesyłają komunikatów
.Tn ICMP
"time exceeded" lub przesyłają je z ttl zbyt małym by nas osiągnąć. 14 \- 17
pracują pod kontrolą kodu 
.Tn MIT
C Gateway, który nie wysyła "time exceeded"s. Bóg jeden wie, co dzieje
się na 12.
.Pp
Cicha bramka 12 w powyższym może być wynikiem błędu w kodzie sieciowym 4.[23]
.Tn BSD
(i jego pochodnych): 4.x (x <= 3) wysyła nieosiągalne komunikaty, używając
ttl pozostałego w oryginalnych datagramach. Zatem, dla bramek, pozostały
ttl wynosi zero,
.Tn ICMP
"time exceeded" nie ma szans dojść z powrotem do nas. Zachowanie tego błędu
jest trochę ciekawsze kiedy pojawi się na systemie docelowym:
.Bd -literal
1  helios.ee.lbl.gov (128.3.112.1)  0 ms  0 ms  0 ms
2  lilac-dmc.Berkeley.EDU (128.32.216.1)  39 ms  19 ms  39 ms
3  lilac-dmc.Berkeley.EDU (128.32.216.1)  19 ms  39 ms  19 ms
4  ccngw-ner-cc.Berkeley.EDU (128.32.136.23)  39 ms  40 ms  19 ms
5  ccn-nerif35.Berkeley.EDU (128.32.168.35)  39 ms  39 ms  39 ms
6  csgw.Berkeley.EDU (128.32.133.254)  39 ms  59 ms  39 ms
7  * * *
8  * * *
9  * * *
10  * * *
11  * * *
12  * * *
13  rip.Berkeley.EDU (128.32.131.22)  59 ms !  39 ms !  39 ms !

.Ed
Zauważ, że jest tu 12 bramek (13 jest ostatecznym celem), a dokładnie
ostatniej połowy listy "brakuje". Co naprawdę się dzieje to to, że
rip (Sun-3 pracujący pod Sun OS3.5) używa ttl z naszych przychodzących
datagramów jako ttl w swoich odpowiedziach
.Tn ICMP.
Tak więc odpowiedź nie dojdzie, bo przekroczy zadany czas (timeout) na drodze
powrotnej (bez wysyłania ostrzeżeń do kogokolwiek, bo dla ICMP nie są
wysyłane ICMP).
Zmieni się to, gdy użyjemy ttl o długości co najmniej dwa razy większej niż
długość ścieżki. Np. rip jest w rzeczywistości odległy tylko o 7 skoków.
Odpowiedź, która wraca z ttl o wartości 1 jest śladem, że
istnieje taki problem. Gdy ttl jest <=1
.Nm Traceroute
za czasem podróży pakietu drukuje dodatkowo znak
.Sy ! .
Ponieważ dystrybutorzy sprzedają sporo oprogramowania przestarzałego
.Pf ( Tn DEC Ns \'s
Ultrix, Sun 3.x) lub
niestandardowego
.Pq Tn HPUX
, oczekuj że możesz spotkać ten problem często i uważaj, wybierając host
docelowy twoich próbek. Innymi możliwymi adnotacjami, występującymi po
wydrukowanym czasie, są
.Sy !H ,
.Sy !N ,
.Sy !P
(otrzymałem niedostępność hosta, sieci (network) lub protokołu),
.Sy !S
lub
.Sy !F
(zawiodła trasa źródła lub niezbędna jest fragmentacja \- żadne z
tych nie powinno nigdy się pojawić). Jeśli prawie wszystkie próbki dadzą
w wyniku jakiś rodzaj nieosiągalności,
.Nm traceroute
podda się i wyjdzie.
.Pp
Program ten jest przeznaczony do stosowania w testowaniu, pomiarach i
zarządzaniu siecią. Powinien być używany głównie do ręcznego izolowania
błędów.
Nie zaleca się wykorzystywania traceroute w automatach (skryptach),
gdyż powoduje on duże obciążenie sieci.
.Sh AUTOR
Zaimplementowane przez Vana Jacobsona wg pomysłu Steve Deering.
Na wyróżnienie zasługuje Philip Wood, Tim Seaver i Ken Adelman.
.Sh ZOBACZ TAKŻE
.Xr netstat 1 ,
.Xr ping 8
.Sh HISTORIA
Komenda
.Nm
jest obecnie w testach.
