.\" {PTM/PR/0.1/23-07-1999/"Wydrukuj datę i czas w formacie RFC822"}
.\" Translation 1999 by Piotr Roszatycki
.\" Hey, Emacs!  This is an -*- nroff -*- source file.
.\" Authors: Ian Jackson
.TH 822\-DATE 1 "14 sierpnia 1996" "Projekt Debiana" "Debian GNU/Linux"
.SH NAZWA
822\-date \- Wydrukuj datę i czas w formacie RFC822
.SH SKŁADNIA
.B 822\-date
.SH OPIS
.B 822\-date
wyświetla bieżącą datę i czas w formacie opisywanym przez dokument RFC822.
Strefa czasowa ma wartość rekomendowaną przez dokument RFC1123.
.SH OPCJE
.B 822\-date
nie wymaga podania żadnej opcji.
.SH BŁĘDY
To polecenie powinno być częścią polecenia
.BR date (1),
.SH ZOBACZ TAKŻE
.I Standard for the Format of ARPA Internet Text Messages
(RFC822),
.br
.I Requirements for Internet Hosts -- Application and Support
(RFC1123) sekcja 5.2.14,
.br
.BR date (1).
.SH AUTOR
.B 822\-date
oraz ten podręcznik napisał Ian Jackson i udostępnił jako public domain.
