.\" {PTM/WK/2000-VI}
.ig
Based on source and sh-utils.info

Copyright (C) 1994, 95, 96 Free Software Foundation, Inc.

Permission is granted to make and distribute verbatim copies of this
manual provided the copyright notice and this permission notice are
preserved on all copies.

Permission is granted to copy and distribute modified versions of
this manual under the conditions for verbatim copying, provided that
the entire resulting derived work is distributed under the terms of a
permission notice identical to this one.

Permission is granted to copy and distribute translations of this
manual into another language, under the above conditions for modified
versions, except that this permission notice may be stated in a
translation approved by the Foundation.
..
.TH FACTOR "1" FSF "maj 2000" "Narzędzia powłokowe GNU 2.0"
.SH NAZWA
factor \- wypisz czynniki pierwsze liczby
.SH SKŁADNIA
.B factor
.RI [ liczba ..]
.br
.B factor
.RB [ \-\-help ]
.RB [ \-\-version ]
.SH OPIS
Ta strona podręcznika man opisuje polecenie \fBfactor\fP w wersji GNU.
.PP
.B Factor
wypisuje czynniki pierwsze zadanej liczby (liczb). Jeśli w wierszu poleceń
nie podano żadnej \fIliczby\fP, to czyta liczby ze standardowego wejścia,
rozdzielone znakami nowej linii, tabulacjami lub spacjami.
.SH OPCJE
.TP
.B \-\-help
Wyświetla informację o stosowaniu programu i dostępnych opcjach,
kończy pracę.
.TP
.B \-\-version
Wyświetla numer wersji programu i kończy pracę.
.SH "ZGŁASZANIE BŁĘDÓW"
Błędy proszę zgłaszać, w jęz.ang., do <bug-sh-utils@gnu.org>.
.SH ZOBACZ TAKŻE
.BR sh-utils (1).
.SH UWAGI
W pakiecie dystrybucyjnym polecenie \fBfactor\fP występuje wyłącznie
w postaci źródłowej.
.PP
Niniejsza strona powstała na podstawie kodu źródłowego i dokumentacji
Texinfo dla narzędzi powłokowych GNU wersji 2.0.
