.\" {PTM/PB/0.1/21-06-1999/"drukuj rzeczywiste i efektywne UID oraz GID"}
.\" poszerzenie i aktualizacja do GNU sh-utils 2.0 PTM/WK/2000-VI
.ig
Transl.note: based on GNU man page id.1 and sh-utils.info

Copyright (C) 1994, 95, 96 Free Software Foundation, Inc.

Permission is granted to make and distribute verbatim copies of this
manual provided the copyright notice and this permission notice are
preserved on all copies.

Permission is granted to copy and distribute modified versions of
this manual under the conditions for verbatim copying, provided that
the entire resulting derived work is distributed under the terms of a
permission notice identical to this one.

Permission is granted to copy and distribute translations of this
manual into another language, under the above conditions for modified
versions, except that this permission notice may be stated in a
translation approved by the Foundation.
..
.TH ID "1" FSF "maj 2000" "Narzędzia powłokowe GNU 2.0"
.SH NAZWA
id - drukuj rzeczywiste i efektywne UID oraz GID
.SH SKŁADNIA
.TP 4
.B id
.RB [ \-gnruG ]
.RB [ \-\-group ]
.RB [ \-\-name ]
.RB [ \-\-real ]
.RB [ \-\-user ]
.br
.RB [ \-\-groups ]
.RB [ \-\-help ]
.RB [ \-\-version ]
.RI [ użytkownik ]
.SH OPIS
Ta strona podręcznika opisuje polecenie \fBid\fR w wersji GNU.
.PP
.B id
wypisuje informację o podanym użytkowniku lub o procesie, który go uruchomił
(w wypadku gdy nie podano użytkownika). Domyślnie drukuje rzeczywisty UID,
rzeczywisty GID, efektywny UID (jeśli jest różny od rzeczywistego UID),
efektywny GID (jeśli jest różny od rzeczywistego GID) oraz dodatkowe grup
dodatkowych. Każda z tych wartości liczbowych jest poprzedzona identyfikującym
ją napisem. Za wartością ID znajduje się odpowiadająca mu nazwa użytkownika
lub grupy, ujęta w nawiasy.
.PP
Opcje powodują, że
.B id
wypisuje tylko część powyższej informacji.
.SH OPCJE
.TP
.BR \-g ", " \-\-group
Wypisuje tylko GID.
.TP
.BR \-G ", " \-\-groups
Drukuje tylko grupy dodatkowe.
.TP
.BR \-n ", " \-\-name
Zamiast numeru ID, wypisuje nazwę użytkownika (lub grupy).
Wymaga
.BR \-u ,
.BR \-g ,
lub
.BR \-G .
.TP
.BR \-r ", " \-\-real
Wypisuje rzeczywisty (zamiast efektywnego) ID użytkownika lub grupy.
Wymaga
.BR \-u ,
.BR \-g ,
lub
.BR \-G .
.TP
.BR \-u ", " \-\-user
Drukuje tylko ID użytkownika.
.TP
.B \-\-help
Wyświetla informację o stosowaniu programu i dostępnych opcjach, kończy
pracę.
.TP
.B \-\-version
Wyświetla numer wersji programu i kończy pracę.
.SH "ZGŁASZANIE BŁĘDÓW"
Błędy proszę zgłaszać, w jęz.ang., do <bug-sh-utils@gnu.org>.
.SH COPYRIGHT
Copyright \(co 1999 Free Software Foundation, Inc.
.br
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.SH ZOBACZ TAKŻE
.BR users (1),
.BR who (1),
.BR sh-utils (1).
.SH OD TŁUMACZA
Zaktualizowano i poszerzono wg dokumentacji Texinfo dla narzędzi powłokowych
GNU wersji 2.0.
