.\" 1999 PTM Przemek Borys
.\" poszerzenie i aktualizacja do GNU sh-utils 2.0 PTM/WK/2000-VI
.ig
Transl.note: based on GNU man page pathchk.1 and sh-utils.info

Copyright (C) 1994, 95, 96 Free Software Foundation, Inc.

Permission is granted to make and distribute verbatim copies of this
manual provided the copyright notice and this permission notice are
preserved on all copies.

Permission is granted to copy and distribute modified versions of
this manual under the conditions for verbatim copying, provided that
the entire resulting derived work is distributed under the terms of a
permission notice identical to this one.

Permission is granted to copy and distribute translations of this
manual into another language, under the above conditions for modified
versions, except that this permission notice may be stated in a
translation approved by the Foundation.
..
.TH PATHCHK "1" FSF "maj 2000" "Narzędzia powłokowe GNU 2.0"
.SH NAZWA
pathchk \- sprawdź czy nazwy plików są prawidłowe lub przenośne
.SH SKŁADNIA
.TP 9
.B pathchk
.RB [ -p ]
.RB [ \-\-portability ]
.RB [ \-\-help ]
.RB [ \-\-version ]
.br
.IR nazwapliku ...
.SH OPIS
Ta strona podręcznika man opisuje polecenie \fBpathchk\fR w wersji GNU.
.PP
Dla każdej
.IR nazwypliku ,
.B pathchk
wypisuje komunikat w wypadku wystąpienia któregokolwiek z określonych
niżej warunków:
.br
\(bu jeden z istniejących w
.I nazwiepliku
katalogów nie posiada prawa przeszukiwania (wykonania)
.br
\(bu długość
.I nazwypliku
jest większa niż dopuszczalna długość nazwy pliku dla danego systemu plików
.br
\(bu długość jednej ze składowych
.IR nazwypliku ,
odpowiadającej nazwie istniejącego katalogu, jest większa niż maksymalna
dopuszczalna w danym systemie plików długość składowej nazwy.
.SH OPCJE
.TP
.BR \-p ", " \-\-portability
Zamiast dokonywania sprawdzeń długości danego systemu plików, testuje
długość nazw plików i ich składowych według norm POSIX.1. Poza tym sprawdza,
czy nazwa pliku nie zawiera nieprzenośnych znaków.
.TP
.B \-\-help
Wyświetla informację o stosowaniu programu i dostępnych opcjach, kończy
pracę.
.TP
.B \-\-version
Wyświetla numer wersji programu i kończy pracę.
.SH KOD ZAKOŃCZENIA
.TP
.B 0
jeśli wszystkie podane nazwy plików przeszły pomyślnie wszystkie testy.
.TP
.B 1
w przeciwnym wypadku
.SH "ZGŁASZANIE BŁĘDÓW"
Błędy proszę zgłaszać, w jęz.ang., do <bug-sh-utils@gnu.org>.
.SH COPYRIGHT
Copyright \(co 1999 Free Software Foundation, Inc.
.br
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.SH ZOBACZ TAKŻE
.BR basename (1),
.BR dirname (1),
.BR sh-utils (1).
.SH OD TŁUMACZA
Zaktualizowano i poszerzono wg dokumentacji Texinfo dla narzędzi powłokowych
GNU wersji 2.0.
