.\" {PTM/PB/0.1/28-09-1998/"zmień powłokę loginową"}
.\"
.\"  chsh.1 -- change your login shell
.\"  (c) 1994 by salvatore valente <svalente@athena.mit.edu>
.\"
.\"  this program is free software.  you can redistribute it and
.\"  modify it under the terms of the gnu general public license.
.\"  there is no warranty.
.\"
.\"  $Author: wojtek2 $
.\"  $Revision: 1.3 $
.\"  $Date: 2001/10/07 15:47:40 $
.\"
.\"  Translation (c) 1998 Przemek Borys <pborys@p-soft.silesia.linux.org.pl>
.TH CHSH 1 "13 października 1994" "chsh" "Linux Reference Manual"
.SH NAZWA
chsh \- zmień powłokę zgłoszeniową
.SH SKŁADNIA
.B chsh
.RB [-s
.IR powłoka ]
.RB [ -l ]
.RB [ -u ]
.RB [ -v ]
.RI [ nazwaużytkownika ]
.SH OPIS
.B chsh
jest używany do zmiany powłoki zgłoszeniowej (login shell) użytkownika.
Jeśli nie podano go w wierszu poleceń,
.B chsh
pyta o niego.
.SS PRAWIDŁOWE POWŁOKI
.B chsh
przyjmie pełną ścieżkę do dowolnego pliku wykonywalnego w systemie. Jednakże
wypisze ostrzeżenie, jeśli powłoka nie jest podana w pliku
.IR /etc/shells .
.SH OPCJE
.TP
.BR \-s ", " \-\-shell
Podaje powłokę zgłoszeniową.
.TP
.BR \-l ", " \-\-list-shells
Wypisuje listę powłok z pliku
.IR /etc/shells .
.TP
.BR \-u ", " \-\-help
Wypisuje informacje o użyciu programu.
.TP
.BR -v ", " \-\-version
Wypisuje wersję programu.
.SH "ZOBACZ TAKŻE"
.BR login (1),
.BR passwd (5),
.BR shells (5)
.SH AUTOR
Salvatore Valente <svalente@mit.edu>
