.TH VLOCK 1 "16 Maja 1996" "Podręcznik Użytkownika Linuksa"
.SH NAZWA
vlock \- program do blokowania wirtualnej konsoli
.SH SKADNIA
.B vlock
.PP
.B vlock [ -a,--all ] [ -c,--current ] [ -h,--help ] [ -v,--version ]
.SH OPIS
.B vlock
jest programem służącym do blokowania jednej lub wielu sesji w konsoli Linuksa. Jest szczególnie przydatny na linuksowych komputerach, do któych konsoli ma dostęp wielu uytkowników. Użytkownik może zablokować swoją(e) sesje, pozwalając innym użytkownikom systemu na normalne użytkowanie innych wirtualnych konsol. Jeśli zaistnieje potrzeba, można zablokować całą konsolę i moliwość przełączania się pomiędzy wirtualnymi terminalami.
.PP
Domyślnie, tylko bieżąca VC (virtual console - wirtualna konsola) jest blokowana. Z opcjami \fB-a,--all\fR wszystkie VC są blokowane. Zablokowane VC nie mogą zostać otwarte bez użycia hasła użytkownika lub roota.  Hasło roota zawsze będzie mogło odblokować jedną lub wiele sesji. Co ważne dla paranoikół, vlock dostarczy niesamowitych wraeżeń wszystkim maniakom, którzy będą próbowali odgadnąć hasło - tak więc nieautoryzowany dostęp do sesji jest wysoce nieprawdopodobny.
.PP
Proszę zauwayć, że możliwe jest całkowite odcięcie się od konsoli przy użyciu opcji \fB-a,--all\fR jeżeli hasło zostanie zapomniane! Jeśli nie jesteś w stanie zalogować sie zdalnie przez terminal szeregowy lub sieć to twardy reset jest jedyną metodą odblokowania sesji.
.PP
\fBvlock\fR działa głównie na sesję konsoli. Istnieje także moliwość blokowania sesji niekonsolowych, jednak nie została ona dobrze przetestowana.
.SH OPCJE
.B -a,--all
.IP
Zamknij wszystkie sesje konsoli i wyłącz moliwość przełączania się pomiędzy VC.
.PP
.B -c,--current
.IP
Zamknij bieżącą sesję (domyślne).
.PP
.B -h,--help
.IP
Wypisz krótki komunikat pomocy.
.PP
.B -v,--version
.IP
Wypisz numer wersji \fBvlock\fR.
.PP
.SH AUTOR
Michael K. Johnson <johnsonm@redhat.com>
.SH TŁUMACZENIE
.br
Projekt Tłumaczenia Manuali
.br
http://ptm.berlios.de
